# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Nathan' do
  pod 'UrbanAirship-iOS-SDK'
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Nathan

  target 'NathanTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NathanUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
